export type City = {
  slug: string;
  name: string;
  state: string;
  region: string;
  areas: string[];
  angle: string;
  competitionNote: string;
  language: string;
  searchNote: string;
};

export const CITIES: City[] = [
  { slug: 'delhi', name: 'Delhi', state: 'Delhi NCR', region: 'North India',
    areas: ['Rajouri Garden', 'Greater Kailash', 'Dwarka', 'Pitampura', 'Lajpat Nagar', 'Rohini'],
    angle: 'Delhi patients compare four or five clinics on Google before they call. Whoever looks most credible on a phone screen wins the appointment.',
    competitionNote: 'Delhi is the most competitive dental market in India — dozens of clinics fight for the same three Map Pack slots in every colony.',
    language: 'English + Hindi', searchNote: 'best dentist in Delhi, dental clinic near me Delhi, root canal cost Delhi' },
  { slug: 'mumbai', name: 'Mumbai', state: 'Maharashtra', region: 'West India',
    areas: ['Andheri', 'Bandra', 'Powai', 'Thane', 'Borivali', 'Lower Parel'],
    angle: 'Mumbai runs on convenience. Patients book the clinic that shows opening hours, a live WhatsApp button and a walkable location — in that order.',
    competitionNote: 'Mumbai clinics compete suburb by suburb, so a single generic "Mumbai" page is not enough — you need area-level content.',
    language: 'English + Marathi + Hindi', searchNote: 'dentist in Andheri, dental clinic Bandra, invisalign cost Mumbai' },
  { slug: 'bangalore', name: 'Bangalore', state: 'Karnataka', region: 'South India',
    areas: ['Indiranagar', 'Koramangala', 'Whitefield', 'HSR Layout', 'Jayanagar', 'Hebbal'],
    angle: 'Bangalore has the most digital-first patient base in India. A slow or template-looking site is an instant disqualification here.',
    competitionNote: 'Tech-corridor clinics in Whitefield and HSR compete on reviews and online booking, not on price.',
    language: 'English + Kannada', searchNote: 'dentist near me Bangalore, dental implant cost Bangalore, aligners Bangalore' },
  { slug: 'hyderabad', name: 'Hyderabad', state: 'Telangana', region: 'South India',
    areas: ['Banjara Hills', 'Gachibowli', 'Kukatpally', 'Madhapur', 'Secunderabad', 'Kondapur'],
    angle: 'Hyderabad has strong cosmetic-dentistry demand. Before-and-after galleries convert better here than anywhere else in India.',
    competitionNote: 'Gachibowli and Madhapur are saturated; older areas like Secunderabad are still winnable with basic local SEO.',
    language: 'English + Telugu + Hindi', searchNote: 'best dental clinic Hyderabad, smile designing Hyderabad, dentist Gachibowli' },
  { slug: 'chennai', name: 'Chennai', state: 'Tamil Nadu', region: 'South India',
    areas: ['T. Nagar', 'Anna Nagar', 'Adyar', 'Velachery', 'OMR', 'Porur'],
    angle: 'Chennai patients research treatment cost heavily before calling. Transparent pricing pages cut your phone-tyre-kicker calls in half.',
    competitionNote: 'Large chains dominate the generic keywords, but neighbourhood keywords are wide open.',
    language: 'English + Tamil', searchNote: 'dentist in Anna Nagar, dental clinic Velachery, braces cost Chennai' },
  { slug: 'pune', name: 'Pune', state: 'Maharashtra', region: 'West India',
    areas: ['Kothrud', 'Baner', 'Viman Nagar', 'Hinjewadi', 'Wakad', 'Kalyani Nagar'],
    angle: 'Pune’s young working population books online at night. If your site has no after-hours booking path, those leads go to a competitor.',
    competitionNote: 'IT-belt areas like Hinjewadi and Wakad are growing faster than the clinics serving them — great time to rank.',
    language: 'English + Marathi', searchNote: 'dentist in Baner, dental clinic Kothrud, teeth whitening Pune' },
  { slug: 'kolkata', name: 'Kolkata', state: 'West Bengal', region: 'East India',
    areas: ['Salt Lake', 'Ballygunge', 'New Town', 'Behala', 'Howrah', 'Park Street'],
    angle: 'Kolkata dental search is under-served — most clinics still have no website at all, which makes ranking unusually cheap here.',
    competitionNote: 'Low competition, high opportunity. A well-built site can hit the Map Pack in under 90 days.',
    language: 'English + Bengali', searchNote: 'dentist in Salt Lake, dental clinic Kolkata, RCT cost Kolkata' },
  { slug: 'ahmedabad', name: 'Ahmedabad', state: 'Gujarat', region: 'West India',
    areas: ['Satellite', 'Prahlad Nagar', 'Bopal', 'Maninagar', 'Vastrapur', 'SG Highway'],
    angle: 'Ahmedabad families choose clinics together. Pages that speak to full-family dentistry and package pricing outperform single-treatment pages.',
    competitionNote: 'SG Highway corridor is competitive; east Ahmedabad is largely unclaimed online.',
    language: 'English + Gujarati', searchNote: 'dental clinic Satellite Ahmedabad, dentist near me Ahmedabad' },
  { slug: 'jaipur', name: 'Jaipur', state: 'Rajasthan', region: 'North India',
    areas: ['Vaishali Nagar', 'Malviya Nagar', 'C-Scheme', 'Mansarovar', 'Jagatpura', 'Tonk Road'],
    angle: 'Jaipur gets meaningful dental-tourism traffic alongside local patients. A bilingual site with clear pricing captures both.',
    competitionNote: 'Vaishali Nagar and Malviya Nagar have real competition; the rest of the city is open.',
    language: 'Hindi + English', searchNote: 'best dentist in Jaipur, dental implant Jaipur cost' },
  { slug: 'lucknow', name: 'Lucknow', state: 'Uttar Pradesh', region: 'North India',
    areas: ['Gomti Nagar', 'Hazratganj', 'Aliganj', 'Indira Nagar', 'Alambagh', 'Jankipuram'],
    angle: 'Lucknow patients search in Hindi far more than clinic owners expect. Hindi content is a genuine ranking advantage here.',
    competitionNote: 'Very few Lucknow clinics have fast, Hindi-ready websites — first mover advantage is real.',
    language: 'Hindi + English', searchNote: 'डेंटिस्ट लखनऊ, dental clinic Gomti Nagar, dentist near me Lucknow' },
  { slug: 'chandigarh', name: 'Chandigarh', state: 'Chandigarh', region: 'North India',
    areas: ['Sector 17', 'Sector 35', 'Mohali', 'Panchkula', 'Sector 8', 'Zirakpur'],
    angle: 'Chandigarh, Mohali and Panchkula are one search market. Ranking across all three tricity areas triples your reach.',
    competitionNote: 'Moderate competition, high-value patients, strong cosmetic and orthodontic demand.',
    language: 'English + Punjabi + Hindi', searchNote: 'dentist Chandigarh sector 35, dental clinic Mohali' },
  { slug: 'indore', name: 'Indore', state: 'Madhya Pradesh', region: 'Central India',
    areas: ['Vijay Nagar', 'Palasia', 'Rau', 'Bhawarkuan', 'Sudama Nagar', 'Scheme 78'],
    angle: 'Indore is one of India’s fastest-growing tier-2 cities and dental search volume is climbing faster than supply of good clinic websites.',
    competitionNote: 'Low competition. Most clinics rely only on Justdial, which is losing traffic every year.',
    language: 'Hindi + English', searchNote: 'dentist in Vijay Nagar Indore, dental clinic Indore' },
  { slug: 'nagpur', name: 'Nagpur', state: 'Maharashtra', region: 'Central India',
    areas: ['Dharampeth', 'Sadar', 'Manish Nagar', 'Wardha Road', 'Civil Lines', 'Pratap Nagar'],
    angle: 'Nagpur patients still call rather than book online, so click-to-call placement matters more than a booking calendar.',
    competitionNote: 'Thin online competition — a Growth package typically outranks the whole city within a quarter.',
    language: 'Marathi + Hindi + English', searchNote: 'dental clinic Dharampeth, best dentist Nagpur' },
  { slug: 'surat', name: 'Surat', state: 'Gujarat', region: 'West India',
    areas: ['Adajan', 'Vesu', 'Piplod', 'Katargam', 'Varachha', 'Athwalines'],
    angle: 'Surat’s business families pay for premium cosmetic work but check credibility hard. Doctor credentials and gallery pages do the selling.',
    competitionNote: 'Vesu and Adajan are the contested zones; Varachha and Katargam are open.',
    language: 'Gujarati + Hindi + English', searchNote: 'dentist in Vesu Surat, dental clinic Adajan' },
  { slug: 'noida', name: 'Noida', state: 'Uttar Pradesh', region: 'Delhi NCR',
    areas: ['Sector 18', 'Sector 62', 'Sector 50', 'Greater Noida', 'Sector 137', 'Noida Extension'],
    angle: 'Noida is sector-driven. A page targeting your specific sector beats a generic "Noida" page every single time.',
    competitionNote: 'High competition in commercial sectors, low in residential extensions.',
    language: 'English + Hindi', searchNote: 'dentist sector 62 Noida, dental clinic Noida extension' },
  { slug: 'gurgaon', name: 'Gurgaon', state: 'Haryana', region: 'Delhi NCR',
    areas: ['DLF Phase 1-5', 'Sohna Road', 'Golf Course Road', 'Sector 56', 'MG Road', 'New Gurgaon'],
    angle: 'Gurgaon has the highest average treatment value in North India. Patients here expect insurance info, EMI options and slick booking.',
    competitionNote: 'Premium market, premium competition — but most clinic sites are still slow and generic.',
    language: 'English + Hindi', searchNote: 'best dentist Gurgaon, invisalign Gurgaon cost, dental clinic DLF' },
  { slug: 'patna', name: 'Patna', state: 'Bihar', region: 'East India',
    areas: ['Boring Road', 'Kankarbagh', 'Patliputra', 'Bailey Road', 'Rajendra Nagar', 'Danapur'],
    angle: 'Patna dental search is growing fast and almost nobody is optimised for it. Hindi-first content wins here decisively.',
    competitionNote: 'Extremely low online competition. This is the easiest major city in India to rank in right now.',
    language: 'Hindi + English', searchNote: 'डेंटिस्ट पटना, best dental clinic Patna, dentist Boring Road' },
  { slug: 'bhopal', name: 'Bhopal', state: 'Madhya Pradesh', region: 'Central India',
    areas: ['Arera Colony', 'MP Nagar', 'Kolar Road', 'Shahpura', 'New Market', 'Ayodhya Bypass'],
    angle: 'Bhopal patients heavily weigh Google reviews. A review-collection system built into your site changes your enquiry volume within weeks.',
    competitionNote: 'Very few optimised clinic sites — the Map Pack is winnable in one quarter.',
    language: 'Hindi + English', searchNote: 'dentist MP Nagar Bhopal, dental clinic Arera Colony' },
  { slug: 'kochi', name: 'Kochi', state: 'Kerala', region: 'South India',
    areas: ['Kakkanad', 'Edappally', 'Panampilly Nagar', 'Vyttila', 'Fort Kochi', 'Palarivattom'],
    angle: 'Kochi serves both local patients and NRI families home on visit — pages that mention NRI-friendly scheduling convert unusually well.',
    competitionNote: 'Moderate competition, strong demand for implants and full-mouth rehab.',
    language: 'English + Malayalam', searchNote: 'dental clinic Kakkanad, best dentist Kochi, implants Kochi' },
  { slug: 'coimbatore', name: 'Coimbatore', state: 'Tamil Nadu', region: 'South India',
    areas: ['RS Puram', 'Peelamedu', 'Saibaba Colony', 'Gandhipuram', 'Vadavalli', 'Singanallur'],
    angle: 'Coimbatore families stay loyal to one clinic for years. Winning the first search is worth a decade of visits.',
    competitionNote: 'Low competition and high patient lifetime value — one of the best ROI cities in India.',
    language: 'Tamil + English', searchNote: 'dentist RS Puram, dental clinic Coimbatore, braces Coimbatore' },
];

export const getCity = (slug: string) => CITIES.find((c) => c.slug === slug);
