import type { Post } from './posts-types';

export const POSTS_C: Post[] = [
  {
    slug: 'best-website-builder-for-dentists-india',
    title: 'Wix vs WordPress vs Custom: The Best Website Option for Indian Dentists',
    metaTitle: 'Best Website Builder for Dentists in India (2026) — Honest Comparison',
    metaDesc: 'Wix, WordPress, GoDaddy or a custom build for your dental clinic? A straight comparison on cost, speed, SEO, ownership and maintenance for Indian clinics.',
    excerpt: 'All four options can produce a website. Only some of them produce patients. Here is the honest trade-off on each.',
    category: 'Comparison',
    date: '2026-04-24',
    readMins: 9,
    takeaways: [
      'DIY builders are cheapest upfront and most expensive over five years.',
      'WordPress is flexible but carries real maintenance and security burden.',
      'Custom builds win on speed, which is a ranking factor.',
      'Ownership of domain and hosting matters more than most clinics realise.',
    ],
    sections: [
      { h: 'The four realistic options', p: [
        'Indian dental clinics essentially choose between: a DIY builder like Wix, Squarespace or GoDaddy; a WordPress site built by a freelancer; a custom-coded site from a studio; or one of the dental-specific website subscription services.',
        'None of them is universally correct. The right answer depends on your budget, your time, your city\'s competitiveness and whether you intend to compete on search at all.',
      ]},
      { h: 'DIY builders (Wix, Squarespace, GoDaddy)', p: [
        '**Cost:** roughly ₹500 to ₹1,500 a month, forever. Over five years that is ₹30,000 to ₹90,000.',
        '**Speed:** typically 40 to 60 on mobile PageSpeed. Builders load large JavaScript bundles to power their drag-and-drop editors, and that cost is passed to your patient\'s phone.',
        '**SEO:** basic controls are present. Advanced schema, fine-grained control and genuinely fast pages are not.',
        '**Time:** you build it. Expect 20 to 40 hours of your own time, which for a practising dentist is the real cost.',
        '**Verdict:** reasonable if you have no budget and need something online this week. It will not win a competitive treatment keyword, and the subscription never ends.',
      ]},
      { h: 'WordPress via a freelancer', p: [
        '**Cost:** ₹8,000 to ₹40,000 to build, plus ₹3,000 to ₹8,000 a year hosting.',
        '**Speed:** highly variable, and less uniformly bad than agencies claim. When we measured 13 Indian clinic sites the median homepage was 536 KB — respectable. But the spread was enormous: the heaviest was 5,672 KB across 153 requests. A plugin-heavy WordPress build is where that weight comes from.',
        '**SEO:** excellent potential with the right plugins and a competent builder. Poor in practice when the builder does not do keyword research.',
        '**Maintenance:** this is the hidden cost. Plugins and core need regular updates. Skipped updates are the single most common reason Indian clinic sites get hacked, injected with spam and delisted by Google.',
        '**Verdict:** the most common choice in India and a perfectly reasonable one — provided you find a builder who does research, keeps the plugin count low, and someone maintains it afterwards.',
      ]},
      { h: 'Dental-specific subscription services', p: [
        '**Cost:** ₹3,000 to ₹15,000 a month.',
        '**What you get:** templates designed for dentistry, sometimes with booking and patient forms included.',
        '**The catch:** you typically do not own the site. Stop paying and it disappears, taking your rankings with it. Content and structure are often near-identical to every other clinic on the platform, which limits how well any of you can rank.',
        '**Verdict:** convenient, and expensive over time. Read the ownership terms very carefully before committing.',
      ]},
      { h: 'Custom builds', p: [
        '**Cost:** ₹15,000 to ₹1,50,000 one time in India, depending on scope.',
        '**Speed:** this is the main advantage. Modern frameworks like Next.js serve pre-built pages from an edge network, so 1 to 2 second mobile loads are normal rather than exceptional. Since page experience is a ranking signal, speed is not vanity.',
        '**SEO:** full control over schema, structure, internal linking and page-level optimisation.',
        '**Maintenance:** minimal. No plugin stack means almost nothing to break or patch.',
        '**Verdict:** the right choice if you intend to compete on search, and the wrong choice if you just need an online business card.',
      ]},
      { h: 'The comparison that actually matters', p: [
        'Over five years, a DIY builder at ₹1,000 a month costs ₹60,000 and produces a slow site you do not fully control. A ₹29,999 custom build plus roughly ₹4,000 a year in domain and hosting costs about ₹49,000 total and produces a fast site you own outright.',
        'The upfront number is what clinic owners compare. The five-year number is what they actually pay.',
        'And the number that dwarfs both: one additional implant patient a year, at ₹25,000 to ₹60,000 per case in most Indian cities, covers the entire difference several times over.',
      ]},
      { h: 'How to decide in one question', p: [
        'Ask yourself: do I want a website, or do I want patients from search?',
        'If it is the first — a place to send people who already know your name — any option works and you should pick the cheapest one you can maintain.',
        'If it is the second, the requirements narrow sharply: fast mobile loading, a page per treatment, proper schema, local SEO, and full ownership. That is achievable on a well-built WordPress site and reliably achievable on a custom build. It is very difficult on a DIY builder.',
      ]},
    ],
    faqs: [
      { q: 'Is WordPress good for a dental clinic website?', a: 'It can be very good, and it is the most common choice in India. The risks are speed and maintenance: a plugin-heavy theme-based build will load slowly, and unpatched plugins are the leading cause of clinic sites being hacked. Insist on a lean build and arrange for someone to keep it updated.' },
      { q: 'Can I move my website later if I change my mind?', a: 'If you own your domain and your content, yes. If you are on a subscription platform where the provider owns the site, migration usually means rebuilding from scratch. Always check who holds the domain registration before you sign anything.' },
      { q: 'Does website speed really affect Google rankings?', a: 'Yes. Google uses mobile page experience, including Core Web Vitals, as a ranking signal. Speed also affects conversion directly — each additional second of load time costs roughly 7% of conversions, which on a clinic doing thirty enquiries a month is a real and permanent loss.' },
    ],
  },
  {
    slug: 'why-dental-website-not-ranking',
    title: 'Why Your Dental Website Is Not Ranking on Google (12 Real Reasons)',
    metaTitle: 'Why Your Dental Website Is Not Ranking on Google — 12 Fixable Reasons',
    metaDesc: 'Twelve technical and strategic reasons Indian dental clinic websites fail to rank, how to diagnose each one yourself, and what to fix first.',
    excerpt: 'You paid for a website, it has been live for a year, and nobody finds it. Here are the twelve reasons that account for almost every case.',
    category: 'SEO',
    date: '2026-04-10',
    readMins: 10,
    takeaways: [
      'Most ranking failures are structural, not competitive.',
      'Check indexing before anything else — some sites are invisible to Google entirely.',
      'One services page cannot rank for ten treatments.',
      'Reviews and profile completeness often matter more than site changes.',
    ],
    sections: [
      { h: 'Start here: is Google even seeing your site?', p: [
        'Search "site:yourclinic.com" on Google. If nothing appears, or only your homepage appears, your problem is not competition — it is indexing, and no amount of content will help until it is fixed.',
        'Common causes: a "noindex" tag left on from development, a robots.txt blocking crawlers, no sitemap submitted, or the site never being verified in Google Search Console. Developers leave the noindex tag on more often than anyone would like to admit.',
        'Fix: create a Google Search Console account, verify the domain, submit your sitemap, and use the URL Inspection tool on your key pages.',
      ]},
      { h: 'Reason 1: you have one page trying to rank for ten treatments', p: [
        'Google matches queries to pages. A single "Services" page listing implants, braces, RCT, whitening, extractions and paediatric dentistry has one title, one H1 and one topic focus. It can compete for approximately one of those.',
        'Fix: build a dedicated page per treatment, each with its own cost section, procedure explanation and FAQ.',
      ]},
      { h: 'Reason 2: your site takes six seconds to load on mobile', p: [
        'Run your URL through Google PageSpeed Insights and read the Mobile score. Below 50 is a serious drag on rankings and a direct conversion loss.',
        'Typical Indian clinic culprits: uncompressed 3MB photographs, a heavy theme, fifteen plugins, and slow shared hosting.',
        'Fix: compress every image, remove unused plugins, move to better hosting — or rebuild on a framework that produces fast pages by default.',
      ]},
      { h: 'Reason 3: your Google Business Profile is incomplete', p: [
        'For local searches, the profile carries more weight than the website. An unclaimed or half-filled profile caps how visible you can be regardless of how good the site is.',
        'Fix: claim it, complete every field, upload twenty real photos, choose your primary category deliberately, post weekly.',
      ]},
      { h: 'Reason 4: you have eleven reviews and your competitor has ninety', p: [
        'Review count and recency are major prominence signals. This gap alone explains a large share of Map Pack failures.',
        'Fix: install a review system — reception QR card plus a post-appointment WhatsApp template. Reply to every review.',
      ]},
      { h: 'Reason 5: your name, address and phone are inconsistent', p: [
        'Different clinic name formats or phone numbers across Google, Justdial, Practo and your website create ambiguity that suppresses local ranking.',
        'Fix: pick one exact format and enforce it everywhere, character for character.',
      ]},
      { h: 'Reason 6: no city or locality signals in your content', p: [
        'If your homepage title says "Home — Smile Care Dental" and your content never names your city or areas, Google has little basis for connecting you to local searches.',
        'Fix: put your city in the homepage title and H1, add area pages with genuinely distinct content, name landmarks and localities naturally throughout.',
      ]},
      { h: 'Reason 7: thin content, three-hundred-word pages', p: [
        'Treatment pages with two paragraphs cannot outrank competitors covering the procedure, cost, recovery, alternatives and objections in depth.',
        'Fix: expand each treatment page to genuinely answer everything a patient would ask before booking. Length is not the goal; completeness is.',
      ]},
      { h: 'Reason 8: duplicate content across your own pages', p: [
        'Area pages created by copying one page and swapping the locality name are detected and largely ignored. So are treatment pages assembled from the same boilerplate.',
        'Fix: write each page distinctly, even if that means having fewer pages.',
      ]},
      { h: 'Reason 9: no internal linking', p: [
        'If your treatment pages are only reachable from a dropdown menu and never linked from each other or from articles, Google reads them as peripheral.',
        'Fix: link related treatments to each other, link articles to relevant treatment pages, and link treatment pages to your booking page.',
      ]},
      { h: 'Reason 10: no schema markup', p: [
        'Without Dentist, MedicalClinic, FAQ and Review schema, Google has to infer what your pages are about. Schema tells it explicitly — and it is what allows AI overviews to quote you directly.',
        'Fix: implement structured data properly and validate it with Google\'s Rich Results Test.',
      ]},
      { h: 'Reason 11: you are targeting keywords nobody searches', p: [
        'Optimising for "premier dental care solutions" is optimising for a phrase no patient has ever typed. Patients search "root canal cost", "dentist near me", "braces price", "tooth pain doctor".',
        'Fix: write for the words patients use, including the blunt ones about cost and pain.',
      ]},
      { h: 'Reason 12: you have not given it enough time', p: [
        'Sometimes the honest answer is that everything is done correctly and it has been six weeks. Local SEO in a tier-2 Indian city takes one to three months to show; in a metro, four to eight.',
        'Fix: check Search Console for impressions. If impressions are climbing while clicks are still low, you are ranking — just not high enough yet. That is progress, and it is very different from being invisible.',
      ]},
    ],
    faqs: [
      { q: 'How do I check if Google has indexed my dental website?', a: 'Search "site:yourdomain.com" on Google. The results are the pages Google has indexed. If pages are missing, verify the site in Google Search Console and use the URL Inspection tool to request indexing and see any errors blocking it.' },
      { q: 'How long should I wait before deciding my SEO is not working?', a: 'Check impressions in Google Search Console rather than rankings. If impressions are rising month over month, the work is landing and you need more time or more depth. If impressions are flat after three months, something structural is wrong and it is worth auditing.' },
      { q: 'Can a new dental clinic rank against established ones?', a: 'Yes, particularly in tier-2 and tier-3 Indian cities where most established clinics have neglected their online presence entirely. A new clinic with a fast site, treatment pages, a complete Google profile and an active review system frequently outranks clinics that have been open for fifteen years.' },
    ],
  },
  {
    slug: 'whatsapp-for-dental-clinics-india',
    title: 'WhatsApp for Dental Clinics in India: Bookings, Reminders and Recall',
    metaTitle: 'WhatsApp for Dental Clinics in India — Bookings, Reminders & Recall',
    metaDesc: 'How Indian dental clinics use WhatsApp to capture after-hours enquiries, cut no-shows, run recall campaigns and collect reviews — with templates you can copy.',
    excerpt: 'Indian patients will message you when they will not call and will not fill a form. Here is how to build a clinic around that.',
    category: 'Growth',
    date: '2026-03-27',
    readMins: 8,
    takeaways: [
      'WhatsApp captures after-hours enquiries a phone number cannot.',
      'Automated reminders measurably reduce no-shows.',
      'Recall messages to dormant patients are the cheapest revenue available.',
      'Never send clinical details or images over unverified numbers.',
    ],
    sections: [
      { h: 'Why WhatsApp beats every other channel in India', p: [
        'There is nothing to learn. No app to download, no account to create, no form to complete, no receptionist to get past. A patient can message at 11pm, in their own language, with a photo of the tooth that hurts.',
        'Compare that to the alternatives. A phone number only works during clinic hours. A contact form asks for four fields and gives no confirmation anyone read it. Email is largely dead for consumer healthcare in India.',
        'This is why every page of a clinic website should have a WhatsApp button with a pre-written message, and why your Google Business Profile appointment link should point at WhatsApp if you do not have real online booking.',
      ]},
      { h: 'Capturing the after-hours patient', p: [
        'Healthcare search peaks in the evening. People deal with a nagging tooth once they are home, fed and no longer at work. Your clinic is closed and your phone rings into an empty room.',
        'If the only option on your website is a phone number, that patient has two choices: remember to call tomorrow, or tap back and try the next clinic. Most take the second.',
        'A WhatsApp button converts that moment into a message sitting in your inbox at 8am. Even if you reply the next morning, you have captured the patient rather than donating them.',
      ]},
      { h: 'Cutting no-shows with reminders', p: [
        'An empty chair costs the same in rent, salary and electricity as a booked one. No-shows are a continuous, quiet loss that most Indian clinics never quantify.',
        'The pattern that works: a confirmation immediately on booking, a reminder 24 hours before, and a short reminder 2 hours before. Every message includes a one-tap reschedule link.',
        'The reschedule link is the important part. Patients who can easily move an appointment do so, instead of silently vanishing — which means you find out in time to refill the slot.',
      ]},
      { h: 'Recall: the cheapest revenue in dentistry', p: [
        'Every clinic has a list of patients who came once, eighteen months ago, and never returned. They are not unhappy. They simply forgot, and nobody reminded them.',
        'A short, non-pushy recall message to that list is the highest-return marketing available to a dental clinic, because these people already trust you and already know where you are.',
        'Something like: "Hi Mrs. Nair, it\'s been about a year since your last cleaning at Smile Care. Most people are due around now. Reply here if you\'d like a slot this month — no rush either way."',
        'Run it in batches of thirty or forty, not hundreds, and space them out. Bulk-blasting from a personal number is the fastest way to get flagged.',
      ]},
      { h: 'Collecting reviews', p: [
        'Send the review request two to four hours after the appointment, with your direct Google review link. Open rates on WhatsApp are dramatically higher than SMS or email, and the patient can reply directly if something went wrong — giving you a chance to fix it before it becomes a public one-star.',
      ]},
      { h: 'Business account vs API: which do you need', p: [
        '**WhatsApp Business (free app):** correct for most single-location clinics. Gives you a business profile, catalogue, quick replies, labels for organising chats and away messages. Manual sending, which is fine at clinic volume.',
        '**WhatsApp Business API:** needed only when you want genuinely automated messaging at scale — automatic reminders triggered by your booking system, for instance. It runs through an approved provider and carries per-message costs set by Meta, typically a few paise per message.',
        'Most clinics under three chairs never need the API. Start with the free app and upgrade only when manual sending becomes the bottleneck.',
      ]},
      { h: 'Rules to follow so you do not get blocked', p: [
        'Only message people who contacted you or are existing patients. Cold messaging gets numbers blocked fast.',
        'Never send clinical details, reports or intraoral images to a number you have not verified belongs to the patient.',
        'Give an easy opt-out and honour it immediately.',
        'Do not send more than one follow-up if someone does not reply.',
        'Keep patient health information inside your clinic management software, not in a WhatsApp chat history on a shared phone.',
      ]},
    ],
    faqs: [
      { q: 'Is WhatsApp Business free for dental clinics?', a: 'The WhatsApp Business app is completely free and sufficient for most clinics. Only the WhatsApp Business API, used for automated messaging at scale, has per-message costs set by Meta — typically a few paise per message, billed through an approved provider.' },
      { q: 'Can I send appointment reminders automatically on WhatsApp?', a: 'Fully automatic reminders require the WhatsApp Business API connected to your booking system. With the free Business app you can save reminder templates as quick replies and send them manually, which takes a few minutes a day and works well for clinics under about thirty appointments daily.' },
      { q: 'Is it safe to discuss treatment on WhatsApp?', a: 'Keep it general. Scheduling, directions, indicative costs and post-treatment care instructions are fine. Do not send reports, radiographs or clinical images to unverified numbers, and keep the actual patient record in your clinic management software rather than in a chat history.' },
    ],
  },
  {
    slug: 'dental-clinic-marketing-ideas-india',
    title: '15 Dental Clinic Marketing Ideas That Actually Work in India',
    metaTitle: '15 Dental Clinic Marketing Ideas for India (2026) — Tested, Low-Cost',
    metaDesc: 'Fifteen practical, low-cost marketing ideas for Indian dental clinics — ranked by effort and return, from Google Business Profile to school camps and recall campaigns.',
    excerpt: 'Ranked by return per rupee and per hour, starting with the ones that cost nothing.',
    category: 'Growth',
    date: '2026-03-12',
    readMins: 9,
    takeaways: [
      'The three highest-return ideas cost nothing but time.',
      'Recall campaigns to existing patients beat any acquisition channel.',
      'Local partnerships outperform paid ads in tier-2 cities.',
      'Avoid anything that violates dental council advertising norms.',
    ],
    sections: [
      { h: 'Free, high return (do these first)', p: [
        '**1. Complete your Google Business Profile.** Claim it, fill every field, add twenty real photos, choose your primary category strategically, post weekly. Highest return per hour of anything on this list.',
        '**2. Install a review system.** A QR card at reception plus a post-appointment WhatsApp template. Twenty to forty reviews in the first month is a normal result, and it moves both ranking and patient choice.',
        '**3. Run a recall campaign.** Message patients who have not visited in twelve to eighteen months. They already trust you. This is the cheapest revenue in dentistry and most clinics never do it.',
        '**4. Answer questions on your Google profile.** Post the ten questions patients actually ask and answer them yourself. That content appears in search results.',
        '**5. Reply to every review.** Two lines each, personal, within 48 hours. Google reads it as activity and prospective patients read your replies more carefully than the reviews.',
      ]},
      { h: 'Low cost, high return', p: [
        '**6. Build treatment-level pages on your website.** One page per treatment, each with cost, procedure and FAQs. This is the structural change that lets you rank for more than one thing.',
        '**7. Add WhatsApp to everything.** Website, Google profile, signboard, visiting card, prescription pad. Indian patients message when they will not call.',
        '**8. Publish two articles a month.** Answer the questions patients search before booking. Slow, compounding, and increasingly quoted by Google AI overviews.',
        '**9. Photograph your actual clinic.** Twenty phone photos of your real reception, chairs, equipment and team. Stock images actively cost you trust with Indian patients.',
        '**10. Set up appointment reminders.** Confirmation, 24-hour and 2-hour reminders with a reschedule link. Directly reduces no-shows, which is revenue you already earned.',
      ]},
      { h: 'Local and offline, still effective', p: [
        '**11. Partner with nearby businesses.** Gyms, salons, schools and corporate offices near your clinic. A simple arrangement — a dental check-up camp for their members or staff — produces warm patients at almost no cost.',
        '**12. School dental camps.** Genuinely useful, well received, and every child goes home with a note carrying your clinic name. Coordinate with the school administration rather than approaching parents directly.',
        '**13. Corporate tie-ups.** Offices in your area often have no dental arrangement. Offer an annual check-up drive. One tie-up with a 200-person office can fill weeks.',
        '**14. Ask for referrals properly.** Most satisfied patients would refer you and never think to. A single sentence at the end of a successful treatment — "if anyone at home needs a check-up, do send them" — measurably works.',
        '**15. Make your signboard readable from across the road.** Unglamorous, and a surprising number of Indian clinics fail at it. Include your WhatsApp number.',
      ]},
      { h: 'What to avoid', p: [
        'Discount-led advertising. It attracts price-sensitive patients who do not return and it sits uncomfortably with dental council advertising norms in most Indian states.',
        'Buying reviews or incentivising them. Detectable, against policy, and profile suspension is far harder to reverse than to avoid.',
        'Guaranteed-result claims in any marketing. Both an ethical problem and a regulatory one.',
        'Spending your first budget on Instagram ads. Patients discover dentists on Google and verify them on Instagram, not the other way round.',
        'Before-and-after images without documented written consent.',
      ]},
      { h: 'A realistic first ninety days', p: [
        '**Days 1 to 7:** Google Business Profile completed, twenty photos uploaded, all existing reviews replied to.',
        '**Days 8 to 21:** review system installed, recall list built and first batch of messages sent.',
        '**Days 22 to 60:** website fixed or rebuilt with treatment pages and WhatsApp buttons throughout.',
        '**Days 61 to 90:** two articles published, one local partnership approached, weekly profile posts running.',
        'None of that requires an advertising budget, and all of it keeps working after you stop actively doing it.',
      ]},
    ],
    faqs: [
      { q: 'Can dentists advertise in India?', a: 'Dental council regulations in India restrict advertising that is solicitous, comparative, or that guarantees results. Informational content — explaining treatments, publishing your qualifications, sharing patient education, maintaining a website and Google listing — is generally accepted practice. Rules vary by state council, so check your own state\'s current guidance before running anything promotional.' },
      { q: 'What is the cheapest way to get new dental patients?', a: 'Recall campaigns to your existing patient list, which costs nothing but time and reaches people who already trust you. After that, a complete Google Business Profile and a systematic review process — both free, both compounding.' },
      { q: 'Do dental camps actually bring patients?', a: 'They do when they are properly targeted and followed up. A camp at a school, gym or office near your clinic produces warm contacts in your actual catchment area. A camp far from your clinic mostly produces goodwill and little else. Always collect contact details with consent and follow up on WhatsApp within a week.' },
    ],
  },
  {
    slug: 'how-to-choose-dental-website-designer-india',
    title: 'How to Choose a Dental Website Designer in India: 10 Questions to Ask',
    metaTitle: 'How to Choose a Dental Website Designer in India — 10 Questions',
    metaDesc: 'Ten questions that separate a good dental website designer from an expensive one in India — on ownership, speed, SEO, revisions, timelines and what happens after launch.',
    excerpt: 'Ask these ten questions before you pay anyone. The weak quotes fall apart on question three.',
    category: 'Hiring',
    date: '2026-02-26',
    readMins: 8,
    takeaways: [
      'Ownership of domain and hosting is non-negotiable — insist on your name.',
      'Ask for a mobile PageSpeed target, in writing.',
      'A quote without keyword research is a quote for a brochure.',
      'Get the post-launch edit cost before you sign.',
    ],
    sections: [
      { h: 'Why this matters more in dentistry than elsewhere', p: [
        'A restaurant with a bad website still gets walk-ins. A dental clinic competing for "dentist near me" against six other clinics in the same locality does not have that cushion. The website and the Google listing are the shopfront for most new patients.',
        'The cost of choosing badly is not the wasted fee. It is the year you spend with a site that produces nothing before you accept it needs redoing.',
      ]},
      { h: 'The ten questions', p: [
        '**1. Whose name will the domain be registered in?** The only acceptable answer is yours. Designers who register domains in their own name — common in India — hold your rankings hostage at renewal time. Ask to see the registrant details after purchase.',
        '**2. What mobile PageSpeed score will the finished site hit?** Anyone who cannot name a target number has not thought about speed. A serious answer is 80 or above on the Mobile tab of PageSpeed Insights. Get it in writing.',
        '**3. Which treatments will get their own page, and how did you decide?** This is where weak quotes collapse. A good answer references what patients in your city actually search and what your competitors are missing. A vague answer means no research was done and you are buying a template.',
        '**4. Is Google Business Profile setup included?** For a dental clinic this drives more calls than the website. If it is not in scope, the highest-return item in local dental marketing is being left out.',
        '**5. Who writes the content?** If the answer is "you send us the text", budget twenty hours of your own time — or accept placeholder copy. Serious quotes include copywriting.',
        '**6. How many design revisions are included?** Look for unlimited revisions before development starts. A fixed "two rounds" is where surprise charges begin.',
        '**7. What is the exact timeline, and what happens if it slips?** Get a date. Indian web projects slipping from three weeks to five months is common enough that it deserves a written commitment.',
        '**8. What does an edit cost after launch?** A clinic making six small changes a year at ₹1,500 each quietly pays ₹9,000 nobody budgeted for. Get the number.',
        '**9. What happens if my rankings drop after launch?** Relevant if you already have a site. The right answer involves a 301 redirect map and Search Console monitoring. If the designer looks blank at "301 redirect", do not let them migrate your site.',
        '**10. Can I speak to two clinics you have built for?** Not a portfolio screenshot — actual clinic owners, on the phone. Anyone confident in their work will arrange it.',
      ]},
      { h: 'Red flags worth walking away from', p: [
        'Guaranteed number-one rankings. Google neither sells nor guarantees positions, so this is either ignorance or dishonesty.',
        'Refusing to state a price until after a "strategy call". Publishing prices is not commercially dangerous; refusing to is a negotiating tactic.',
        'A portfolio of clinic sites that are all visibly the same template with different logos.',
        'No mention of Google Business Profile anywhere in the proposal.',
        'Requiring a compulsory monthly retainer for the website to keep functioning.',
        'Pressure to decide today because of an "offer expiring".',
      ]},
      { h: 'Green flags', p: [
        'They audit your existing presence before quoting, and tell you honestly if you do not need a rebuild.',
        'They publish their prices.',
        'They talk about treatment pages and search terms rather than colours and animations.',
        'They register the domain in your name without being asked.',
        'They give you a written speed target and a written timeline.',
        'They hand over full admin access to every account they create for you.',
      ]},
      { h: 'What a fair price looks like in India', p: [
        'For a single-location clinic wanting real search performance, ₹15,000 to ₹50,000 one time is the productive range in 2026. Below that you are buying a template; above it you should be getting multi-location support, real booking infrastructure or an ongoing content programme.',
        'Compare quotes on what is inside them — page count, treatment research, Business Profile work, speed target, ownership and post-launch support — not on the headline number. Two quotes twenty thousand rupees apart are frequently describing entirely different products.',
      ]},
    ],
    faqs: [
      { q: 'Should I hire a freelancer or an agency for my dental website?', a: 'Either can work. Freelancers are cheaper and often faster but may disappear after launch and rarely do keyword research. Agencies cost more and add account-management layers you may not need. What matters more than the label is whether they answer the ten questions above convincingly.' },
      { q: 'How do I check a designer\'s previous work?', a: 'Do not accept screenshots. Ask for live URLs, then open each one on your phone and run it through Google PageSpeed Insights. Search the clinic name plus city on Google and see whether it actually ranks. That takes ten minutes and tells you more than any portfolio page.' },
      { q: 'What should I never pay for upfront?', a: 'Never pay 100% in advance. Standard terms in India are 50% to start and 50% on handover of the live, working site. If a provider insists on full payment before you have seen anything, that is the strongest signal available to you.' },
    ],
  },
];
