import type { Post } from './posts-types';

export const POSTS_B: Post[] = [
  {
    slug: 'how-to-get-more-dental-patients-online',
    title: 'How to Get More Dental Patients Online in India (Without Ads)',
    metaTitle: 'How to Get More Dental Patients Online in India — 2026 Playbook',
    metaDesc: 'A practical, ad-free playbook for Indian dental clinics: where patients actually search, the five channels that matter, and the order to fix them in.',
    excerpt: 'Nine out of ten clinic owners start with Instagram. Here is the order that actually produces booked appointments.',
    category: 'Growth',
    date: '2026-06-05',
    readMins: 10,
    takeaways: [
      'Fix Google Business Profile before anything else — it is free and fastest.',
      'Reviews compound; content compounds; ads stop the day you stop paying.',
      'WhatsApp converts better than any form for Indian patients.',
      'Instagram builds trust but rarely produces first-time discovery.',
    ],
    sections: [
      { h: 'Where Indian patients actually look for a dentist', p: [
        'The sequence is remarkably consistent. Something hurts, or a family member mentions a treatment. The person opens Google on a phone and searches "dentist near me" or the specific treatment plus their locality.',
        'They look at the three Map Pack listings. They compare star ratings and review counts. They tap one or two, glance at the photos, maybe open the website. Then they either call, message on WhatsApp, or go back and try the next one.',
        'The whole thing takes under three minutes and happens dozens of times a week in your locality. Notice what is not in that sequence: Instagram, Facebook, printed pamphlets, and hoardings. Those channels have a role, but it is reinforcement, not discovery.',
      ]},
      { h: 'Channel one: Google Business Profile (start here, always)', p: [
        'It is free, it drives more direct calls than your website, and profile fixes show effects within two to three weeks — faster than anything else available to you.',
        'Claim it, verify it, fill in every field, upload twenty real photos, choose your primary category strategically, and reply to every review. If you do nothing else from this article, do this.',
      ]},
      { h: 'Channel two: reviews, systematically', p: [
        'Review count and recency drive both ranking and patient choice. A clinic with 4.3 stars from 120 reviews will consistently beat 5.0 from 8.',
        'The system that works: a QR card at reception linking directly to your Google review form, plus a WhatsApp message a few hours after each appointment. Not a reminder to your staff — an actual artefact and an actual template.',
        'Clinics that install this properly typically add 20 to 40 reviews in the first month, which is often enough on its own to enter the Map Pack in a tier-2 city.',
      ]},
      { h: 'Channel three: a website with treatment-level pages', p: [
        'Your website has two jobs. First, convince the patient who just tapped through from Google that you are credible — that judgement takes about eight seconds and is driven by load speed, real photos and clarity. Second, rank independently for treatment searches.',
        'The second job requires structure. One page per treatment, each with the cost range, the procedure explained in plain language, recovery expectations and FAQs. Fourteen treatments listed on one page rank for approximately one thing. Fourteen pages rank for fourteen.',
      ]},
      { h: 'Channel four: WhatsApp as the conversion layer', p: [
        'Indian patients will message on WhatsApp when they will not fill a form and will not call. There is nothing to learn, no wait, no receptionist to get past, and they can do it at 11pm.',
        'Put a WhatsApp button on every page with a pre-written message so the patient does not have to compose one. Add it to your Google Business Profile as the appointment link. Put your WhatsApp number on your signboard.',
        'Respond fast. The clinic that replies in ten minutes wins the patient the clinic that replies tomorrow was going to get.',
      ]},
      { h: 'Channel five: content that answers real questions', p: [
        'Patients search questions constantly: "is root canal painful", "how long do dental implants last", "braces vs aligners cost", "when should a child first see a dentist".',
        'Answering those properly on your own site does three things: it ranks for long-tail searches with no competition, it gets quoted by Google AI overviews, and it builds trust before the patient ever walks in.',
        'Two articles a month, written honestly and without marketing language, compounds into serious traffic within a year. This is slow and it is the highest-return slow thing available.',
      ]},
      { h: 'Where social media actually fits', p: [
        'Instagram and Facebook are poor discovery channels for dentistry — almost nobody finds their dentist by scrolling. They are excellent reinforcement channels. A patient who found you on Google will often check your Instagram before booking, and an active, human, non-salesy feed converts them.',
        'So: post consistently, show real work and real people, but do not mistake it for a patient acquisition channel. Do not spend your first ten thousand rupees there.',
      ]},
      { h: 'The order to do all of this in', p: [
        'Week one: claim and complete your Google Business Profile, upload photos, reply to existing reviews.',
        'Week two: install the review system — QR card and WhatsApp template.',
        'Month one to two: fix or build the website with treatment-level pages and WhatsApp buttons everywhere.',
        'Month two onward: publish two articles a month, keep posting weekly on your profile, keep collecting reviews.',
        'Nothing in that list requires ad spend. All of it compounds. That is the entire difference between marketing that stops when you stop paying and marketing that keeps working.',
      ]},
    ],
    faqs: [
      { q: 'Should dental clinics run Google Ads in India?', a: 'Ads produce enquiries immediately and stop producing them the day the budget stops. They can make sense to bridge the first few months while organic work matures, or for a new clinic with no reviews yet. As a permanent strategy they are expensive, because dental keyword costs in Indian metros have risen sharply and you are renting visibility you could own.' },
      { q: 'How long before online marketing brings patients?', a: 'Google Business Profile fixes often produce more calls within two to four weeks. Reviews compound over one to three months. Website rankings for treatment keywords typically build over three to six months, faster in tier-2 cities. Anyone promising results in a week is describing ads, not organic growth.' },
      { q: 'Is Instagram worth it for a dental clinic?', a: 'As a trust-building layer, yes. As a discovery channel, largely no — patients find dentists on Google and verify them on Instagram, not the other way around. Post consistently but do not prioritise it over your Google presence.' },
    ],
  },
  {
    slug: 'dental-website-checklist',
    title: 'The 47-Point Dental Website Checklist (India, 2026)',
    metaTitle: '47-Point Dental Website Checklist for Indian Clinics — Free Guide',
    metaDesc: 'A complete audit checklist for dental clinic websites in India: technical, local SEO, content, conversion and trust. Score your own site in twenty minutes.',
    excerpt: 'Go through this with your website open. Anything you cannot tick is costing you patients right now.',
    category: 'Checklist',
    date: '2026-05-22',
    readMins: 11,
    takeaways: [
      'Technical and local items matter more than design items.',
      'Most Indian clinic sites fail on speed, treatment pages and booking path.',
      'Score under 30 of 47 means a rebuild is usually cheaper than patching.',
    ],
    sections: [
      { h: 'How to use this', p: [
        'Open your clinic website on a phone, not a laptop — that is where more than 80% of your patients see it. Go through each section and tick what is genuinely true, not what you intended.',
        'Above 40 of 47: you are in good shape, fix the gaps. 30 to 40: targeted fixes will produce real gains. Below 30: a rebuild usually costs less than patching, because the underlying structure is the problem.',
      ]},
      { h: 'Technical foundation (10 points)', p: [
        '1. Loads in under 2.5 seconds on a 4G mobile connection.',
        '2. Scores 80 or above on Google PageSpeed Insights for mobile.',
        '3. Has a valid SSL certificate — the padlock, no warnings.',
        '4. Readable on a phone without pinching or horizontal scrolling.',
        '5. Images are compressed and in modern formats, not 4MB JPEGs.',
        '6. Has an XML sitemap submitted to Google Search Console.',
        '7. Has a robots.txt that does not accidentally block the site.',
        '8. Every page has a unique title tag under 60 characters.',
        '9. Every page has a unique meta description under 160 characters.',
        '10. No broken links or 404 errors on primary navigation paths.',
      ]},
      { h: 'Local SEO (9 points)', p: [
        '11. Clinic name, address and phone appear in the footer of every page.',
        '12. That NAP matches your Google Business Profile exactly, character for character.',
        '13. Google Maps embed on the contact page with a directions link.',
        '14. LocalBusiness or Dentist schema markup implemented.',
        '15. City name appears naturally in your homepage title and H1.',
        '16. Separate pages for each area or locality you serve.',
        '17. Google Business Profile linked from the site and vice versa.',
        '18. Opening hours published on the site and matching the profile.',
        '19. Listed with consistent NAP on at least five Indian directories.',
      ]},
      { h: 'Content and structure (10 points)', p: [
        '20. A separate page for each major treatment, not one services list.',
        '21. Each treatment page includes an indicative cost or cost range.',
        '22. Each treatment page explains the procedure in plain language.',
        '23. Each treatment page has its own FAQ section.',
        '24. Doctor profile pages with qualifications, registration and experience.',
        '25. An About page that reads like humans wrote it.',
        '26. A blog or patient-education section, updated at least monthly.',
        '27. FAQ schema markup so Google AI can quote your answers.',
        '28. Content available in the local language where a large share of patients search that way.',
        '29. No duplicated content across pages with only the city name swapped.',
      ]},
      { h: 'Conversion path (9 points)', p: [
        '30. WhatsApp button visible on every page, with a pre-written message.',
        '31. Click-to-call phone number in the header, tappable on mobile.',
        '32. An enquiry form with four fields or fewer.',
        '33. A clear primary call to action above the fold on every page.',
        '34. Online booking or a clear appointment request path.',
        '35. Form submissions reach you within seconds, reliably.',
        '36. A visible response-time promise ("we reply within a few hours").',
        '37. Emergency or same-day contact clearly signposted.',
        '38. Directions and parking information for patients arriving by car.',
      ]},
      { h: 'Trust and credibility (9 points)', p: [
        '39. Real photographs of your actual clinic, not stock images.',
        '40. Real photographs of your actual team, with names.',
        '41. Google reviews displayed or linked prominently.',
        '42. Before-and-after gallery with documented patient consent.',
        '43. Dental council registration number displayed.',
        '44. Qualifications and specialisations stated clearly.',
        '45. A privacy policy page that actually describes your practices.',
        '46. Terms of use page.',
        '47. No broken English, placeholder text, or "Lorem ipsum" anywhere.',
      ]},
      { h: 'What to fix first if you scored badly', p: [
        'Order matters more than volume. Fix in this sequence: page speed, then WhatsApp and click-to-call, then treatment pages, then Google Business Profile consistency, then reviews display, then content.',
        'That order is deliberate — the first three change conversion on traffic you already have, which produces results in days. The rest changes how much traffic you get, which takes months.',
      ]},
    ],
    faqs: [
      { q: 'How do I test my dental website speed?', a: 'Open Google PageSpeed Insights, paste your URL and read the Mobile tab, not Desktop. Anything under 50 is a serious problem, 50 to 79 needs work, 80 and above is healthy. Also just open your site on your own phone on mobile data and count the seconds.' },
      { q: 'Do I really need a separate page for every treatment?', a: 'If you want to rank for treatment searches, yes. Google matches queries to pages, not to websites. One page listing fourteen treatments competes for roughly one keyword cluster. Fourteen focused pages compete for fourteen.' },
      { q: 'Is a blog necessary for a dental clinic website?', a: 'Not strictly, but it is the cheapest way to rank for the hundreds of long-tail questions patients ask before booking. Two honest articles a month compounds into meaningful traffic within a year, and Google AI overviews increasingly quote this kind of content directly.' },
    ],
  },
  {
    slug: 'how-to-get-google-reviews-dental-clinic',
    title: 'How to Get More Google Reviews for Your Dental Clinic (Ethically)',
    metaTitle: 'How to Get More Google Reviews for a Dental Clinic in India',
    metaDesc: 'A practical system for Indian dental clinics to collect genuine Google reviews: timing, QR cards, WhatsApp templates, handling negatives, and what gets you suspended.',
    excerpt: 'Reviews are the strongest ranking signal you fully control. Here is the system that produces 20 to 40 in the first month.',
    category: 'Reviews',
    date: '2026-05-08',
    readMins: 8,
    takeaways: [
      'Ask within hours of the appointment, not days.',
      'Reduce it to one tap: QR card plus direct review link.',
      'Reply to every review — Google counts it as activity.',
      'Never buy reviews or offer discounts for them.',
    ],
    sections: [
      { h: 'Why reviews outrank almost everything else', p: [
        'Google uses "prominence" as one of three local ranking factors, and review count, review recency and average rating are its most measurable components. They are also the first thing a patient looks at.',
        'Here is the uncomfortable arithmetic: a clinic with a 4.3 average from 130 reviews beats a clinic with a perfect 5.0 from 9 reviews, both in Google rankings and in patient choice. Volume and recency matter more than perfection.',
        'Unlike almost every other ranking factor, this one is entirely within your control and costs nothing.',
      ]},
      { h: 'Get the timing right', p: [
        'The single biggest determinant of whether a patient leaves a review is when you ask. The window is the same day, ideally within a few hours of the appointment while relief and gratitude are still fresh.',
        'Ask a week later and the emotional moment has passed. Ask during a painful procedure and you will get an honest but unhelpful answer. Ask at the reception desk while they are paying and it feels transactional.',
        'The sequence that works: a warm verbal mention as they leave ("if today went well, a Google review really helps other patients find us"), then a WhatsApp message with the direct link two to four hours later.',
      ]},
      { h: 'Reduce it to one tap', p: [
        'Every additional step loses a large share of people. "Search for us on Google and leave a review" is four steps and most patients never complete it.',
        'Get your direct review link: open your Google Business Profile, find "Ask for reviews", copy the short link. That link opens the review box directly.',
        'Turn it into two artefacts. First, a printed card at reception with a QR code for that link and one line of text — patients scan it while waiting for change. Second, a saved WhatsApp template your front desk sends after each appointment.',
      ]},
      { h: 'A WhatsApp template that does not feel pushy', p: [
        'Keep it short, name them, and make the ask once. Something like:',
        '"Hi Mr. Verma, hope you\'re feeling comfortable after today\'s treatment. If you have a moment, a quick Google review helps other patients in the area find us — takes about 30 seconds: [link]. Either way, do message here if anything feels off. — Dr. Sharma, Smile Care Dental"',
        'Note what it does: uses their name, references the specific visit, states the time cost honestly, gives them a non-review way to raise a problem, and signs off as a person. Do not follow up more than once.',
      ]},
      { h: 'Reply to every single review', p: [
        'Google treats owner responses as an activity signal, and prospective patients read your replies more attentively than the reviews themselves.',
        'For positive reviews: thank them by name, reference something specific, keep it to two lines. Copy-pasted "Thank you for your feedback!" across forty reviews reads as automated and undermines the credibility the reviews were meant to build.',
        'For negative reviews: respond within 24 hours, never disclose any clinical detail or even confirm they were a patient, acknowledge the experience, apologise that it fell short, and give a direct contact to resolve it offline. Never argue. A calm reply to an angry review has converted more patients than most marketing anyone has ever paid for.',
      ]},
      { h: 'What will get your profile suspended', p: [
        'Buying reviews from a service. They are detectable through pattern analysis and the penalty falls on you, not the vendor.',
        'Offering a discount, free cleaning or any incentive in exchange for a review. This violates Google policy explicitly.',
        'Review gating — asking patients privately whether they are happy and only sending the review link to the ones who say yes. Google prohibits this.',
        'Asking staff, family or friends who were never patients to review the clinic. Reviews from accounts with no location history and no other activity are the easiest fake pattern for Google to detect.',
        'Setting up a tablet in your clinic for patients to review on. Multiple reviews from a single IP address is a classic flag.',
      ]},
      { h: 'A realistic target', p: [
        'Look up the three clinics currently in the Map Pack for your main treatment in your area. Note their review counts. That is your target, not an abstract number.',
        'A clinic seeing 15 patients a day that asks properly can realistically convert 10 to 15% of them into reviews. That is roughly 30 to 45 reviews a month at full effort, and 20 to 40 in a first month is a normal result once the system is installed.',
        'Then keep going. Recency matters — a clinic with 200 reviews where the newest is eight months old looks worse to Google than one with 80 where the newest is this week.',
      ]},
    ],
    faqs: [
      { q: 'Can I offer a discount for a Google review?', a: 'No. Incentivising reviews violates Google policy and risks removal of the reviews and suspension of your profile. You can absolutely ask, remind and make it easy — you just cannot pay for it in any form, including discounts, free cleanings or entries into a draw.' },
      { q: 'What should I do about a fake negative review?', a: 'Report it through your Business Profile as a policy violation, respond publicly with a calm professional note that does not accuse anyone, and keep collecting genuine reviews so it gets diluted. Google removes clearly fraudulent reviews on appeal, though it often takes several weeks.' },
      { q: 'How many reviews does a dental clinic need to rank?', a: 'There is no absolute number, only a competitive one. Check the review counts of the clinics currently ranking in your area and aim above them. In most Indian cities, 50 or more recent reviews with a 4.5+ average puts a clinic firmly in contention.' },
      { q: 'Should I ask for reviews on WhatsApp or SMS?', a: 'WhatsApp, in India, without question. Open rates are dramatically higher, the link preview renders properly, and patients can reply to you directly if something was wrong — which gives you a chance to fix it before it becomes a public review.' },
    ],
  },
];
